/** Extra Spanish fallbacks for visit-template tasks filled from Title/Description. */
export const TEMPLATE_TASK_TITLE_ES_EXTRA: Record<string, string> = {
  'Air refreshners refilling': 'Relleno de ambientadores',
  'All doors cleanliness': 'Limpieza de todas las puertas',
  'All trash cans or almost empty (common bathrooms, kitchen and common area)': 'Todas las papeleras vacías o casi vacías (baños comunes, cocina y zona común)',
  'All windows clean and locked': 'Todas las ventanas limpias y cerradas',
  'Apartment entrance door': 'Puerta de entrada del apartamento',
  'At least 15 glasses, wine glasses, and mugs on each side of the countertop available for guests, and that they’re upside down': 'Al menos 15 vasos, copas y tazas a cada lado de la encimera, disponibles para los huéspedes y boca abajo',
  'Back up items': 'Artículos de respaldo',
  'Balcony': 'Balcón',
  'Bathroom deep clean': 'Limpieza profunda del baño',
  'Bathroom restocking: paper towels, toilet paper (4), shampoo, body wash, and hand soap': 'Reposición del baño: toallas de papel, papel higiénico (4), champú, gel y jabón de manos',
  'Bathroom soaps and toiler paper restocking (4)': 'Reposición de jabones y papel higiénico del baño (4)',
  'Bathroom stock: hand paper towels, toilet paper (4), shampoo, body wash, and hand soap': 'Stock del baño: toallas de papel, papel higiénico (4), champú, gel y jabón de manos',
  'Bathroom stock: toilet paper (3), shampoo, body wash, and hand soap': 'Stock del baño: papel higiénico (3), champú, gel y jabón de manos',
  'Beam cleaning': 'Limpieza de vigas',
  'Beam neard entrance door cleaning': 'Limpieza de la viga cerca de la puerta de entrada',
  'Beams': 'Vigas',
  'Bedroom and stairs rug': 'Alfombra del dormitorio y de la escalera',
  'Bedroom and stairs rug cleaning': 'Limpieza de la alfombra del dormitorio y de la escalera',
  'Below the beds cleanliness': 'Limpieza debajo de las camas',
  'Boiler pressure >1.4': 'Presión de la caldera >1.4',
  'Cabinets cleaning': 'Limpieza de armarios',
  'Ceiling fan': 'Ventilador de techo',
  'Ceiling fan cleaning': 'Limpieza del ventilador de techo',
  'Ceiling fans cleaning': 'Limpieza de los ventiladores de techo',
  'Celing fan works': 'El ventilador de techo funciona',
  'Celing fans work': 'Los ventiladores de techo funcionan',
  'Change linen': 'Cambiar ropa de cama',
  'Change towels': 'Cambiar toallas',
  'Check if storage downstairs needs sweeping (only if necessary)': 'Comprobar si el trastero de abajo necesita barrerse (solo si es necesario)',
  'Clean all the doors, since they’re black and show marks easily': 'Limpiar todas las puertas, ya que son negras y marcan con facilidad',
  'Clean the area above the counter': 'Limpiar la zona encima de la encimera',
  'Clean the balcony and close it (so nothing is visible from the kitchen)': 'Limpiar el balcón y cerrarlo (para que no se vea nada desde la cocina)',
  'Clean the black base of the coffee table in the living room': 'Limpiar la base negra de la mesa de centro del salón',
  'Clean the brick ceiling in the hallway (especially the black part)': 'Limpiar el techo de ladrillo del pasillo (sobre todo la parte negra)',
  'Clean the cutlery drawer': 'Limpiar el cajón de los cubiertos',
  'Clean the fans and leave them running (if not cold enough)': 'Limpiar los ventiladores y dejarlos encendidos (si no hace suficiente fresco)',
  'Clean the leather chairs in the work area': 'Limpiar las sillas de cuero de la zona de trabajo',
  'Clean the library/games area': 'Limpiar la zona de biblioteca/juegos',
  'Clean the mirror on the entrance': 'Limpiar el espejo de la entrada',
  'Cleaning': 'Limpieza',
  'Cleaning equipment to the left of the fridge': 'Utensilios de limpieza a la izquierda de la nevera',
  'Cleaning on top of the fridge': 'Limpieza encima de la nevera',
  'Cleaning under the sofa': 'Limpieza debajo del sofá',
  'Clock is working': 'El reloj funciona',
  'Close the door with the code when leaving to lock it': 'Cerrar la puerta con el código al salir para dejarla bloqueada',
  'Coffee machines full of coffee and water, trays empty': 'Cafeteras llenas de café y agua, bandejas vacías',
  'Coffee machines maintenance': 'Mantenimiento de las cafeteras',
  'Coffee makers are fully stocked with water and coffee, and empty the tray of water and coffee grounds': 'Las cafeteras están llenas de agua y café, y la bandeja de agua y posos está vacía',
  'Coffee stains near the wall': 'Manchas de café cerca de la pared',
  'Coffee table glass cleaning': 'Limpieza del cristal de la mesa de centro',
  'Common bathrooms condition (not perfect, but decent)': 'Estado de los baños comunes (no perfecto, pero decente)',
  'Common bathrooms condition (perfect condition since the clean was deep)': 'Estado de los baños comunes (perfecto, porque la limpieza fue profunda)',
  'Common bathrooms restocked: hand paper towels, toilet paper (4), hand soap, shampoo and shower gel': 'Baños comunes repuestos: toallas de papel, papel higiénico (4), jabón de manos, champú y gel de ducha',
  'Common bathrooms restocking: hand paper towels, toilet paper (4), hand soap, shampoo and shower gel': 'Reposición de baños comunes: toallas de papel, papel higiénico (4), jabón de manos, champú y gel de ducha',
  'Countertop': 'Encimera',
  'Deep bathroom cleaning': 'Limpieza profunda del baño',
  'Deep common bathrooms cleaning': 'Limpieza profunda de los baños comunes',
  'Degreaser': 'Desengrasante',
  'Desk chair stability': 'Estabilidad de la silla de escritorio',
  'Dishwasher': 'Lavavajillas',
  'Dishwashers': 'Lavavajillas',
  'Dishwashers empty and all in its place (put some dishes in the cabinets so the drawers aren’t too heavy)': 'Lavavajillas vacíos y todo en su sitio (guardar algunos platos en los armarios para que los cajones no pesen demasiado)',
  'Dishwashers empty or with just a few things': 'Lavavajillas vacíos o con pocas cosas',
  'Double check there\'s no retouch needed in common bathrooms. If it\'s the case, report on Slack': 'Comprobar que los baños comunes no necesitan un retoque. Si lo necesitan, avisar por Slack',
  'Dust and spiderwebs in the bricks wall': 'Polvo y telarañas en el muro de ladrillo',
  'Electric blinds': 'Persianas eléctricas',
  'Electric blinds work': 'Las persianas eléctricas funcionan',
  'Empty all garbage cans (kitchen, common area and common bathrooms)': 'Vaciar todas las papeleras (cocina, zona común y baños comunes)',
  'Empty all trash cans (common bathrooms, kitchen and common area)': 'Vaciar todas las papeleras (baños comunes, cocina y zona común)',
  'Entrance floor': 'Suelo de la entrada',
  'Entrance floor cleaning': 'Limpieza del suelo de la entrada',
  'External grilles cleaning': 'Limpieza de las rejas exteriores',
  'Floors cleaning': 'Limpieza de suelos',
  'Floors cleanliness': 'Limpieza de los suelos',
  'Freezer': 'Congelador',
  'Freezers empty (the little lid on top)': 'Congeladores vacíos (la tapita de arriba)',
  'Furniture in its place': 'Muebles en su sitio',
  'General order in storage': 'Orden general del trastero',
  'Gently vacuum the blue fabric piece in the kitchen (brush setting)': 'Aspirar con cuidado la pieza de tela azul de la cocina (ajuste de cepillo)',
  'Gifts': 'Regalos',
  'Glasses, wine glasses, mugs and little spoons are clean and complete (there should be at least one extra of each item based on the apartment’s capacity)': 'Vasos, copas, tazas y cucharillas están limpios y completos (debe haber al menos uno extra de cada artículo según la capacidad del apartamento)',
  'Hair dryer, trays and toothbrush holder are present': 'Hay secador, bandejas y portacepillos',
  'Hairs and stains in linen': 'Pelos y manchas en la ropa de cama',
  'Hangers are present (enough amount)': 'Hay perchas (cantidad suficiente)',
  'Heaters are off': 'Los calefactores están apagados',
  'Humidities check': 'Comprobación de humedades',
  'If someone left a dish sponge, remove it': 'Si alguien dejó un estropajo, retirarlo',
  'If the cake tray is already empty, wash it and store it in the upper kitchen cabinets. If there are still sweets on it, make sure they are all properly covered on the tray or add more as per the instructions for the day': 'Si la bandeja de dulces ya está vacía, lavarla y guardarla en los armarios altos de la cocina. Si aún hay dulces, asegurarse de que estén bien cubiertos o añadir más según las instrucciones del día',
  'If the next guests are arriving the same day and it’s summer, leave the fan on': 'Si los siguientes huéspedes llegan el mismo día y es verano, dejar el ventilador encendido',
  'In summer, keep the electric blinds in the rooms almost completely closed (leave a gap of about 5 fingers)': 'En verano, dejar las persianas eléctricas de las habitaciones casi cerradas (un hueco de unos 5 dedos)',
  'Kettle cleaning': 'Limpieza del hervidor',
  'Keys': 'Llaves',
  'Kitchen box and mini fridge shelf empty': 'Caja de cocina y estante del minibar vacíos',
  'Kitchen garbage containers empty': 'Contenedores de basura de la cocina vacíos',
  'Kitchen restocked: sugar, olive oil, stevia, salt, kitchen paper rolls in both sides of the counter': 'Cocina repuesta: azúcar, aceite de oliva, stevia, sal y rollos de papel de cocina a ambos lados de la encimera',
  'Kitchen restocking: olive oil, sugar, stevia, salt, dish soap, paper towels on both sides of the counter, dish soap': 'Reposición de cocina: aceite de oliva, azúcar, stevia, sal, jabón de platos y papel de cocina a ambos lados de la encimera',
  'Kitchen restocking: sugar, olive oil, stevia, salt, dish soap, kitchen paper rolls in both sides of the counter': 'Reposición de cocina: azúcar, aceite de oliva, stevia, sal, jabón de platos y rollos de papel de cocina a ambos lados de la encimera',
  'Kitchen stock: olive oil, sugar, stevia, salt, paper towels on both sides of the counter, dish soap': 'Stock de cocina: aceite de oliva, azúcar, stevia, sal, papel de cocina a ambos lados de la encimera y jabón de platos',
  'Knifes': 'Cuchillos',
  'Lamps and artwork cleaning': 'Limpieza de lámparas y cuadros',
  'Lamps cleaning': 'Limpieza de lámparas',
  'Leave showers with the movable showerhead facing the wall and the floor drain cover in place after cleaning the hair trap': 'Dejar las duchas con el rociador orientado a la pared y la tapa del desagüe puesta después de limpiar el recogepelos',
  'Leave the living rooms fan on if not cold enough': 'Dejar el ventilador del salón encendido si no hace suficiente fresco',
  'Lightbulbs check': 'Comprobación de bombillas',
  'Linen and towels change': 'Cambio de ropa de cama y toallas',
  'Make sure the coffee makers are fully stocked with water and coffee + empty the tray of water and coffee grounds (upon arrival and departure)': 'Asegurarse de que las cafeteras estén llenas de agua y café y vaciar la bandeja de agua y posos (al llegar y al salir)',
  'Make sure the teapot, toaster, and microwave are empty and clean': 'Asegurarse de que tetera, tostadora y microondas estén vacíos y limpios',
  'Microwave': 'Microondas',
  'Microwave empty and clean': 'Microondas vacío y limpio',
  'Mini fridge empty and clean': 'Minibar vacío y limpio',
  'Music background': 'Música de fondo',
  'Netflix': 'Netflix',
  'Noise detector': 'Detector de ruido',
  'Patio': 'Patio',
  'Patio clean and locked': 'Patio limpio y cerrado',
  'Photo of the thermostat (light on and off)': 'Foto del termostato (luz encendida y apagada)',
  'Place glasses, wine glasses, and mugs upside down in the rack on the kitchen counter': 'Colocar vasos, copas y tazas boca abajo en el soporte de la encimera',
  'Portable heaters under each bed': 'Calefactores portátiles debajo de cada cama',
  'Quick bathroom check and restocking if needed': 'Revisión rápida del baño y reposición si hace falta',
  'Report if there\'s no music in the background': 'Avisar si no hay música de fondo',
  'Report on Slack if more cleaning than the scheduled is needed in order to leave all in good condition': 'Avisar por Slack si hace falta más limpieza de la prevista para dejarlo todo en buen estado',
  'Rugs': 'Alfombras',
  'Run the dishwasher and put everything back in its place': 'Poner el lavavajillas y guardar todo en su sitio',
  'Shampoo, shower gel and gel soap': 'Champú, gel de ducha y jabón',
  'Sink drainage lid in place': 'Tapa del desagüe del lavabo colocada',
  'Sofa': 'Sofá',
  'Sofa cleaning': 'Limpieza del sofá',
  'Spiderwebs checking': 'Comprobación de telarañas',
  'Storage condition (upstairs and downstairs)': 'Estado del trastero (arriba y abajo)',
  'TV / Dining table and chairs': 'TV / Mesa y sillas de comedor',
  'Unclogging': 'Desatascar',
  'Vacuum': 'Aspiradora',
  'Vacuum floors': 'Aspirar suelos',
  'Vacuum in the closet in front of bathroom': 'Aspiradora en el armario frente al baño',
  'Vacuum the fabric chairs': 'Aspirar las sillas tapizadas',
  'Vacuum under one of the beds': 'Aspirar debajo de una de las camas',
  'Verify cleaning between the 2 mattresses of the bed': 'Comprobar la limpieza entre los 2 colchones de la cama',
  'Wardrobes are empty and clean': 'Los armarios están vacíos y limpios',
  'Washing machine, refrigerator, oven, and microwave are empty and clean': 'Lavadora, nevera, horno y microondas están vacíos y limpios',
  'Water the plants if necessary': 'Regar las plantas si es necesario',
  'Welcome kit': 'Kit de bienvenida',
  'Welcome kit assembling': 'Montaje del kit de bienvenida',
  'White doors in living room and bedroom remain open': 'Las puertas blancas del salón y el dormitorio quedan abiertas',
  'Wifi signs in place': 'Carteles de wifi colocados',
  'Window cleaning': 'Limpieza de ventanas',
  'Window in the door well closed': 'La ventana de la puerta está bien cerrada',
  'Wooden trays and toothbrush container': 'Bandejas de madera y recipiente del cepillo',
}

export const TEMPLATE_TASK_DESCRIPTION_ES_EXTRA: Record<string, string> = {
  'Functionality': 'Funcionamiento',
  'In shower with half of content at least (all bathrooms) + hidden set': 'En la ducha, al menos a la mitad (todos los baños) + juego oculto',
}
